"""
orientation_generator.py: Symmetry-aware orientation analysis and reference generation.

This module analyzes bulk structures to identify symmetrically distinct Miller 
indices and generates oriented reference POSCARs using a 'Uniform Depth' 
architecture for compatible HPC job array execution.
"""

from math import gcd
from pathlib import Path
import re
from functools import reduce

import numpy as np
from pymatgen.core import Structure
from pymatgen.core.surface import (
    SlabGenerator,
    get_symmetrically_distinct_miller_indices,
)
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from .metadata import MetadataManager
from .utils import miller_label


def symmetry_scan(structure: Structure, symprecs=(1e-4, 1e-3, 5e-3, 1e-2, 5e-2)):
    """
    Report detected symmetry across a range of tolerances for debugging.
    Ensure the chosen symprec is stable for the crystal system.
    """
    print(f"{'Symprec':<10} | {'Crystal System':<20} | {'Spacegroup'}")
    print("-" * 50)
    for symprec in symprecs:
        sga = SpacegroupAnalyzer(structure, symprec=symprec)
        try:
            crystal_sys = sga.get_crystal_system()
            symbol = sga.get_space_group_symbol()
            print(f"{symprec:<10.1e} | {crystal_sys:<20} | {symbol}")
        except Exception as exc:
            print(f"{symprec:<10.1e} | ERROR: {exc}")


def check_symmetry(structure: Structure, symprec=1e-3, diagnostic_symprec=1e-2):
    """
    Check whether the assigned crystal system depends strongly on tolerance.
    Issue a warning if a discrepancy is found but do not alter behavior.
    """
    sga_main = SpacegroupAnalyzer(structure, symprec=symprec)
    sga_diag = SpacegroupAnalyzer(structure, symprec=diagnostic_symprec)

    sys_main = sga_main.get_crystal_system()
    sys_diag = sga_diag.get_crystal_system()

    if sys_main != sys_diag:
        print("WARNING: Symmetry sensitivity detected!")
        print(f"  - main symprec ({symprec}): {sys_main}")
        print(f"  - diagnostic symprec ({diagnostic_symprec}): {sys_diag}")
    return sga_main

def parse_miller_index(value: str) -> tuple[int, int, int]:
    """Parse ``001``, ``1n10``, or comma-separated Miller-index notation."""
    cleaned = value.strip().replace("(", "").replace(")", "")
    cleaned = cleaned.replace("[", "").replace("]", "")

    if "," in cleaned or " " in cleaned:
        parts = [part for part in re.split(r"[\s,]+", cleaned) if part]
    else:
        parts = re.findall(r"n?\d", cleaned.lower())
        if "".join(parts) != cleaned.lower():
            raise ValueError

    if len(parts) != 3:
        raise ValueError

    def parse_component(component: str) -> int:
        component = component.lower()
        if component.startswith("n"):
            return -int(component[1:])
        return int(component)

    hkl = tuple(parse_component(part) for part in parts)
    if hkl == (0, 0, 0):
        raise ValueError
    return hkl


def _canonical_hkl(hkl) -> tuple[int, int, int]:
    """Reduce an HKL triplet and treat opposite plane normals as equivalent."""
    rounded = tuple(int(round(float(value))) for value in hkl)
    divisor = reduce(gcd, (abs(value) for value in rounded if value != 0))
    reduced = tuple(value // divisor for value in rounded)

    for value in reduced:
        if value < 0:
            return tuple(-item for item in reduced)
        if value > 0:
            return reduced
    raise ValueError("The Miller index (0, 0, 0) is invalid.")


def _equivalent_hkls(
    hkl: tuple[int, int, int],
    symmetry_operations,
) -> set[tuple[int, int, int]]:
    """Return normalized Miller indices generated by the structure's point group."""
    hkl_vector = np.asarray(hkl, dtype=float)
    equivalents = set()

    for operation in symmetry_operations:
        rotation = np.asarray(operation.rotation_matrix, dtype=float)
        transformed = np.linalg.inv(rotation).T @ hkl_vector
        equivalents.add(_canonical_hkl(transformed))

    return equivalents


def _select_requested_orientations(
    requested_orientations: list[str],
    distinct_indices: list[tuple[int, int, int]],
    symmetry_operations,
) -> list[tuple[int, int, int]]:
    """Validate requested HKLs and remove symmetry-equivalent duplicates."""
    representatives = {
        _canonical_hkl(index): index
        for index in distinct_indices
    }
    available = " ".join(miller_label(index) for index in distinct_indices)

    selected = []
    used_representatives = set()

    for raw_value in requested_orientations:
        try:
            requested_hkl = parse_miller_index(raw_value)
        except (TypeError, ValueError):
            raise ValueError(
                f"Invalid Miller index {raw_value!r}. Use notation such as 001, 111, or 1n10."
            ) from None

        matching_representative = next(
            (
                representative
                for representative in representatives
                if representative in _equivalent_hkls(requested_hkl, symmetry_operations)
            ),
            None,
        )

        if matching_representative is None:
            raise ValueError(
                f"Orientation {raw_value!r} is not available with max_miller_index=1. "
                f"Available symmetry-unique orientations: {available}"
            )

        if matching_representative in used_representatives:
            print(
                f"Orientation {raw_value} is symmetry-equivalent to an already requested "
                "orientation. Skipping duplicate."
            )
            continue

        used_representatives.add(matching_representative)
        selected.append(requested_hkl)

    return selected


def generate_orientations(
    input_file: str | Path,
    output_dir: str | Path = "oriented_structures",
    max_miller_index: int = 1,
    symprec: float = 1e-3,
    diagnostic_symprec: float = 1e-2,
    primitive: bool = True,
    requested_orientations: list[str] | None = None,
) -> list[str]:
    """
    Generate reference POSCARs for symmetry-unique or explicitly requested orientations.

    Returns the generated orientation directory labels so downstream strain generation
    can be restricted to the same selection.
    """
    input_path = Path(input_file)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    structure = Structure.from_file(input_path)
    sga = check_symmetry(structure, symprec, diagnostic_symprec)
    conventional_structure = sga.get_conventional_standard_structure()
    metadata = MetadataManager(output_path, input_file=input_path.name)

    distinct_indices = list(
        get_symmetrically_distinct_miller_indices(
            conventional_structure,
            max_miller_index,
        )
    )

    if requested_orientations:
        indices = _select_requested_orientations(
            requested_orientations,
            distinct_indices,
            sga.get_point_group_operations(cartesian=False),
        )
    else:
        indices = distinct_indices

    generated_labels = []

    for hkl in indices:
        label = miller_label(hkl)
        generated_labels.append(label)
        hkl_dir = output_path / label
        existing_metadata = metadata.get_orientation_metadata(label)

        needs_regeneration = True
        if hkl_dir.exists() and (hkl_dir / "POSCAR_reference").exists() and existing_metadata:
            parameters_match = (
                existing_metadata.get("primitive") == primitive
                and existing_metadata.get("miller_index") == list(hkl)
            )
            if parameters_match:
                print(f"Orientation {label} matches existing metadata. Skipping.")
                needs_regeneration = False
            else:
                print(f"Orientation {label} exists but its settings differ. Regenerating.")

        if needs_regeneration:
            hkl_dir.mkdir(exist_ok=True)

            generator = SlabGenerator(
                conventional_structure,
                miller_index=hkl,
                min_slab_size=1,
                min_vacuum_size=1,
                primitive=primitive,
                in_unit_planes=True,
            )

            oriented_structure = generator.oriented_unit_cell
            oriented_structure.to(
                fmt="POSCAR",
                filename=hkl_dir / "POSCAR_reference",
            )
            oriented_structure.to(
                fmt="cif",
                filename=hkl_dir / f"{label}.cif",
            )

            parameters = {
                "miller_index": list(hkl),
                "primitive": primitive,
                "symprec": symprec,
                "source_file": input_path.name,
                "spacegroup": sga.get_space_group_symbol(),
                "crystal_system": sga.get_crystal_system(),
            }
            metadata.upsert_orientation(label, parameters)
            print(f"Generated reference for {label} in {hkl_dir}")

    print(f"\nOrientation generation complete. Manifest: {metadata.path}")
    return generated_labels
